"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { useDemo } from "@/context/demo-provider";
import { selectHQ } from "@/lib/hq-selectors";
import { clockDuration, kitchenTime } from "@/lib/kitchen-rush";
import { formatDuration, formatPercentage } from "@/lib/format";
import { KITCHEN_EPOCH } from "@/data/demo-kitchen";
import { HQMap } from "./hq-map";
import styles from "./hq-operations.module.css";

type Selection = { type: "order" | "rider" | "exception"; id: string } | { type: "kitchen" | "signal" };
export function HQOperations() {
  const demo = useDemo();
  const data = selectHQ(demo);
  const [selection, setSelection] = useState<Selection>({ type: "order", id: "GS-2847" });
  const [filter, setFilter] = useState<"all" | "active">("all");
  const dialog = useRef<HTMLDialogElement>(null);
  const trigger = useRef<HTMLElement | null>(null);
  const open = (value: Selection) => { trigger.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setSelection(value); dialog.current?.showModal(); };
  const openHero = () => open({ type: "order", id: demo.currentOrder.id });
  const order = selection.type === "order" ? data.orders.find(order => order.id === selection.id) : undefined;
  const rider = selection.type === "rider" ? data.riders.find(rider => rider.id === selection.id) : undefined;
  const exception = selection.type === "exception" ? data.exceptions.find(exception => exception.id === selection.id) : undefined;
  const drawerTitle = order?.id ?? rider?.name ?? exception?.title ?? (selection.type === "kitchen" ? "Vijay Nagar" : "GO SERVE Signal");
  const displayTime = (at: string) => kitchenTime(Math.round((Date.parse(at) - Date.parse(KITCHEN_EPOCH)) / 1000), true);
  const sync = <div className={styles.syncValues}><div><span>FOOD {data.sync.actualFood ? "READY" : "TARGET"}</span><strong>{data.sync.foodAt === null ? "—" : kitchenTime(data.sync.foodAt, true)}</strong></div><div><span>RIDER {data.sync.actualArrival ? "ARRIVED" : "ARRIVAL"}</span><strong>{data.sync.arrivalAt === null ? "—" : kitchenTime(data.sync.arrivalAt, true)}</strong></div><div><span>{data.sync.gap === null ? "WAIT" : data.sync.gap >= 0 ? "RIDER WAIT" : "FOOD HOLD"}</span><strong>{data.sync.gap === null ? "—" : `${Math.abs(data.sync.gap)}s`}</strong></div></div>;
  const rows = filter === "active" ? data.orders.filter(order => order.active) : data.orders;
  const metricValues = [{ value: data.activeOrders, label: "active orders", note: "Vijay Nagar" }, { value: formatPercentage(demo.networkMetrics.sla), label: "delivery SLA", note: "network snapshot" }, { value: formatDuration(demo.networkMetrics.averageDeliverySeconds), label: "avg delivery", note: "network snapshot" }, { value: data.kitchensOnline.toString().padStart(2,"0"), label: "kitchen online", note: "observed zone" }, { value: data.activeRiders, label: "riders active", note: `${data.riders.length} in roster sample` }, { value: data.exceptions.length.toString().padStart(2,"0"), label: "exceptions", note: "review + planning" }];
  return <div className={styles.hq}>
    <header className={styles.header}><Link href="/" className={styles.brand} aria-label="GO SERVE entry"><span>g.</span><div>GO SERVE<small>HQ / LIVE OPERATIONS</small></div></Link><div className={styles.location}><h1>Vijay Nagar<span>.</span></h1><small>INDORE · DINNER RUSH</small></div><div className={styles.health}><i />{data.health}<small>SIMULATED · OBSERVATIONAL</small></div><time>{kitchenTime(data.now)}<span>:{String((3 + data.now) % 60).padStart(2,"0")}</span></time></header>
    <main id="main" className={styles.main}>
      <section className={styles.metrics} aria-label="Live operating metrics">{metricValues.map(metric => <div key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span><small>{metric.note}</small></div>)}</section>
      <div className={styles.operating}>
        <section className={styles.neighbourhood} aria-labelledby="map-heading"><div className={styles.sectionHeading}><h2 id="map-heading">THE NEIGHBOURHOOD</h2><span>One zone. One operating picture.</span></div><HQMap data={data} onOrder={openHero} onKitchen={() => open({ type: "kitchen" })} onRider={id => open({ type: "rider", id })} /><button className={styles.syncButton} onClick={openHero}><div className={styles.syncHeading}><span>GS-2847 / HANDOFF</span><span>{data.sync.label} ↗</span></div>{sync}</button></section>
        <section className={styles.stream} aria-labelledby="stream-heading"><div className={styles.sectionHeading}><h2 id="stream-heading">ORDER STREAM</h2><div className={styles.filters} role="group" aria-label="Order stream filter"><button aria-pressed={filter === "all"} onClick={() => setFilter("all")}>All {data.orders.length}</button><button aria-pressed={filter === "active"} onClick={() => setFilter("active")}>Active {data.activeOrders}</button></div></div><div className={styles.columns} aria-hidden="true"><span>ORDER / CUSTOMER</span><span>STAGE / RIDER</span><span>TIMING</span></div><div className={styles.orderList} aria-label="Live orders">{rows.map(row => <button key={row.id} className={`${styles.orderRow} ${row.canonical ? styles.canonical : ""}`} onClick={() => open({ type: "order", id: row.id })} aria-label={`Open order ${row.id}, ${row.stage}`}><span><strong>{row.id}{row.canonical && <i />}</strong><small>{row.customer} · {row.dish}</small></span><span><b>{row.stage}</b><small>{row.rider.split(" ")[0]}</small></span><span><b>{row.timing}</b><small className={row.risk === "Past target" ? styles.amber : ""}>{row.risk}</small></span></button>)}</div><p className={styles.streamNote}>Canonical transaction + Kitchen rush snapshot · scroll for all orders</p></section>
      </div>
      <div className={styles.network}>
        <section aria-labelledby="kitchen-heading"><div className={styles.sectionHeading}><h2 id="kitchen-heading">KITCHEN NETWORK</h2><span>{data.kitchensOnline} observed</span></div><button className={styles.kitchenSummary} onClick={() => open({ type: "kitchen" })}><span><strong>GO SERVE — Vijay Nagar</strong><small>{data.kitchen.active} in kitchen · {formatPercentage(demo.networkMetrics.sla)} network SLA</small></span><span>↗</span></button><div className={styles.loads}>{data.loads.map(load => <div key={load.label}><span>{load.label}</span><div role="progressbar" aria-label={`${load.label} station load`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={load.value}><i style={{ width: `${load.value}%` }} /></div><b>{load.value}%</b></div>)}</div></section>
        <section aria-labelledby="riders-heading"><div className={styles.sectionHeading}><h2 id="riders-heading">RIDER NETWORK</h2><span>{data.riders.length} shown / {data.activeRiders} active network</span></div><div className={styles.riderList}>{data.riders.map(rider => <button key={rider.id} onClick={() => open({ type: "rider", id: rider.id })} aria-label={`Open rider ${rider.name}`}><span>{rider.name}<small>{rider.displayOrder ?? "Vijay Nagar"}</small></span><span>{rider.displayState}<small>{rider.eta ?? "Roster snapshot"}</small></span><span>↗</span></button>)}</div></section>
        <section aria-labelledby="exceptions-heading"><div className={styles.sectionHeading}><h2 id="exceptions-heading">EXCEPTIONS</h2><span>{data.exceptions.length} to review</span></div>{data.exceptions.map(exception => <button key={exception.id} className={styles.exception} onClick={() => open({ type: "exception", id: exception.id })} aria-label={`Open exception ${exception.title}`}><span><strong>{exception.title}</strong><small>{exception.detail}</small></span><span>{exception.tag} ↗</span></button>)}</section>
      </div>
      <div className={styles.outlook}>
        <section className={styles.forecast} aria-labelledby="forecast-heading"><div className={styles.sectionHeading}><h2 id="forecast-heading">NEXT 30 MIN</h2><span>Illustrative slots / 5 min</span></div><div className={styles.forecastBody}><svg viewBox="0 0 450 72" role="img" aria-label={`Illustrative forecast: demand rises from 18 to 28 slots; rider capacity tightens below demand at plus ${data.forecast.find(point => point.demand > point.riders)?.minute} minutes; kitchen capacity remains above demand`}><path d="M5 60H445M5 12H445" stroke="#29372e" fill="none" />{(["kitchen", "riders", "demand"] as const).map(key => <polyline key={key} points={data.forecast.map(point => `${5 + point.minute / 30 * 440},${60 - (point[key] - 16) * 3}`).join(" ")} fill="none" stroke={key === "demand" ? "#b5d6bf" : key === "kitchen" ? "#8b9488" : "#c4b99a"} strokeWidth={key === "demand" ? 2.5 : 1.5} strokeDasharray={key === "riders" ? "4 4" : undefined} />)}</svg><div className={styles.legend}><span>━ Demand</span><span>━ Kitchen</span><span>┄ Riders</span></div></div><div className={styles.axis}><span>Now</span><span>+15m</span><span>+30m</span></div></section>
        <button className={styles.signal} onClick={() => open({ type: "signal" })}><span>↳</span><div><span>GO SERVE SIGNAL</span><p>{data.signal}</p></div><span>↗</span></button>
      </div>
    </main>
    <dialog ref={dialog} className={styles.drawer} aria-labelledby="hq-detail-title" onClose={() => trigger.current?.isConnected && trigger.current.focus({ preventScroll: true })} onClick={event => { if (event.target === event.currentTarget) dialog.current?.close(); }}><div className={styles.drawerInner}><div className={styles.drawerTop}><span>OPERATING DETAIL / {selection.type.toUpperCase()}</span><button aria-label="Close HQ detail" onClick={() => dialog.current?.close()}>×</button></div><h2 id="hq-detail-title">{drawerTitle}</h2>
      {order && <><p className={styles.drawerState}>{order.stage} · {order.risk}</p><dl className={styles.facts}><div><dt>Customer</dt><dd>{order.customer}</dd></div><div><dt>Kitchen</dt><dd>GO SERVE Vijay Nagar</dd></div><div className={styles.fullFact}><dt>Item</dt><dd>{order.dish}</dd></div><div><dt>{order.canonical && !demo.deliveryAssignment ? "Scheduled rider" : "Rider"}</dt><dd>{order.rider}</dd></div><div><dt>{order.canonical ? "Target delivery" : "Preparation"}</dt><dd>{order.canonical ? `${Math.round(demo.currentOrder.promisedSeconds / 60)} minutes` : order.timing}</dd></div></dl>{order.canonical ? <><section className={styles.drawerSync}><div className={styles.syncHeading}><span>SYNCHRONIZATION</span><span>{data.sync.label}</span></div>{sync}<p>{data.sync.gap === null ? "The canonical order has not entered the Kitchen timing plan." : `${data.sync.actualFood ? "Recorded food readiness" : "Planned food readiness"} and ${data.sync.actualArrival ? "recorded rider arrival" : "planned rider arrival"}. ${data.sync.gap >= 0 ? "Rider wait" : "Food hold"} is their timestamp difference.`}</p></section><h3 className={styles.timelineHeading}>TRANSACTION TIMELINE</h3><ol className={styles.timeline}>{data.timeline.map((step, index) => <li key={step.label} className={step.at ? styles.recorded : ""}><span>{String(index + 1).padStart(2,"0")}</span><span>{step.label}</span><time>{step.at ? displayTime(step.at) : "Pending"}</time></li>)}</ol><p className={styles.detailFoot}>Shared state: {demo.currentOrder.status} · elapsed {clockDuration(data.elapsed)}. Timeline entries are recorded milestones, not inferred completion.</p></> : <p className={styles.detailFoot}>Supporting Kitchen rush job. This fixture has a current stage and pickup plan, but no canonical customer transaction history.</p>}</>}
      {rider && <><p className={styles.drawerState}>{rider.displayState}</p><dl className={styles.facts}><div><dt>Mission</dt><dd>{rider.displayOrder ?? "No assignment"}</dd></div><div><dt>Zone</dt><dd>Vijay Nagar</dd></div><div><dt>Arrival / travel</dt><dd>{rider.eta ?? "Not tracked in snapshot"}</dd></div><div><dt>Deliveries today</dt><dd>{rider.deliveriesToday}</dd></div></dl><p className={styles.detailFoot}>{rider.id === "ravi" ? "Ravi’s mission is shared with Rider OS. HQ observes it without dispatching or changing the order." : "A sample from the existing rider roster. Positions are illustrative, not live GPS."}</p></>}
      {selection.type === "kitchen" && <><p className={styles.drawerState}>{demo.kitchen.status} · Dinner rush</p><dl className={styles.facts}><div><dt>Active in kitchen</dt><dd>{data.kitchen.active}</dd></div><div><dt>Preparing</dt><dd>{data.kitchen.preparing}</dd></div><div><dt>Assembly / pack</dt><dd>{data.kitchen.finishing}</dd></div><div><dt>Ready for pickup</dt><dd>{data.kitchen.ready}</dd></div></dl><div className={styles.loads}>{data.loads.map(load => <div key={load.label}><span>{load.label}</span><div><i style={{ width: `${load.value}%` }} /></div><b>{load.value}%</b></div>)}</div><p className={styles.detailFoot}>Loads derive from the same Kitchen jobs. Only Vijay Nagar is observed here; no additional kitchens have been invented.</p></>}
      {exception && <><p className={styles.drawerState}>{exception.tag} · {exception.detail}</p><p className={styles.explanation}>{exception.explanation}</p><p className={styles.detailFoot}>Observation only. No inventory, order or assignment has been changed.</p></>}
      {selection.type === "signal" && <><p className={styles.explanation}>{data.signal}</p><h3 className={styles.timelineHeading}>WHY NOW</h3><p className={styles.detailFoot}>{data.hero.stage === "Not placed" ? "GS-2847 has not been placed. A preparation and pickup window will be available once the order is released." : `GS-2847 is ${data.hero.stage.toLowerCase()}. Keep the Kitchen and Rider handoff milestones aligned.`}</p><p className={styles.detailFoot}>Next 30 minutes: demand rises, Kitchen capacity remains above demand, and rider capacity tightens. Review supply before the forecast crossover at +{data.forecast.find(point => point.demand > point.riders)?.minute}m.</p></>}
    </div></dialog>
  </div>;
}
