"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { useDemo } from "@/context/demo-provider";
import { selectIntelligence } from "@/lib/intelligence-selectors";
import { clockDuration, kitchenTime } from "@/lib/kitchen-rush";
import styles from "./intelligence.module.css";

type Projection = ReturnType<typeof selectIntelligence>;
const time = (value: number | null) => value === null ? "—" : kitchenTime(value, true);
function Synchronization({ data }: { data: Projection }) {
  if (!data.planned) return <div className={styles.emptyTimeline}><span>KITCHEN</span><div /><strong>Awaiting the shared timing plan</strong><div /><span>RIDER</span><p>Order entry establishes preparation, pickup and delivery windows.</p></div>;
  const end = Math.max(data.promiseAt!, data.deliveryAt!, data.now, data.foodAt!, data.arrivalAt!) + 45;
  const begin = Math.min(data.start, data.now, 0);
  const x = (value: number) => 130 + (value - begin) / (end - begin) * 910;
  const rows = [{ label: "KITCHEN", y: 52, start: data.start, end: data.foodAt!, color: "#b9d0aa", text: "Food ready", actual: data.hq.sync.actualFood }, { label: "RAVI", y: 105, start: Math.min(data.now, data.arrivalAt!), end: data.arrivalAt!, color: "#c7bba1", text: "Rider arrival", actual: data.hq.sync.actualArrival }];
  return <div className={styles.timelineScroll}><svg className={styles.timeline} viewBox="0 0 1100 220" role="img" aria-label={`Shared timing axis. Kitchen start ${time(data.start)}. Food ready ${time(data.foodAt)}. Rider arrival ${time(data.arrivalAt)}. Handoff ${time(data.handoffAt)}. Customer delivery ${time(data.deliveryAt)}. Promise ${time(data.promiseAt)}. Now ${time(data.now)}.`}>
    {[0, 0.25, 0.5, 0.75, 1].map(t => <g key={t}><line x1={130 + t * 910} x2={130 + t * 910} y1="32" y2="173" stroke="#2c3930" strokeDasharray="2 5" /><text x={130 + t * 910} y="206" fill="#9ba69b" fontSize="11" textAnchor="middle">{kitchenTime(begin + (end - begin) * t)}</text></g>)}
    <rect x={x(Math.min(data.foodAt!, data.arrivalAt!)) - 6} y="34" width={Math.max(12, Math.abs(x(data.foodAt!) - x(data.arrivalAt!)) + 12)} height="92" rx="5" fill="#b9d0aa" opacity="0.07" />
    <line x1={x(data.now)} x2={x(data.now)} y1="24" y2="176" stroke="#f2f0e8" strokeDasharray="3 4" /><text x={x(data.now)} y="14" textAnchor="middle" fill="#f2f0e8" fontSize="10">NOW</text>
    {rows.map(row => <g key={row.label}><text x="0" y={row.y + 4} fill="#aeb8ab" fontSize="11" letterSpacing="1.5">{row.label}</text><line x1={x(row.start)} x2={x(row.end)} y1={row.y} y2={row.y} stroke={row.color} strokeWidth="4" /><circle cx={x(row.end)} cy={row.y} r="5" fill={row.actual ? row.color : "#152219"} stroke={row.color} strokeWidth="2" /><text x={x(row.end)} y={row.y - 13} fill={row.color} textAnchor="middle" fontSize="12">{row.text} {time(row.end)}</text><path d={`M${x(row.end)} ${row.y + 6} L${x(data.handoffAt!)} 152`} fill="none" stroke={row.color} opacity="0.55" /></g>)}
    <text x="0" y="156" fill="#aeb8ab" fontSize="11" letterSpacing="1.5">DELIVERY</text><line x1={x(data.handoffAt!)} x2={x(data.deliveryAt!)} y1="152" y2="152" stroke="#91b496" strokeWidth="3" /><circle cx={x(data.handoffAt!)} cy="152" r="5" fill={data.pickedUp ? "#e9ece0" : "#152219"} stroke="#e9ece0" strokeWidth="2" /><text x={x(data.handoffAt!)} y="180" fill="#e9ece0" fontSize="11" textAnchor="middle">Handoff {time(data.handoffAt)}</text>
    <circle cx={x(data.deliveryAt!)} cy="152" r="5" fill={data.completed ? "#b9d0aa" : "#152219"} stroke="#b9d0aa" strokeWidth="2" /><text x={x(data.deliveryAt!)} y="136" textAnchor="middle" fill="#b9d0aa" fontSize="11">Customer {time(data.deliveryAt)}</text><line x1={x(data.promiseAt!)} x2={x(data.promiseAt!)} y1="36" y2="178" stroke="#d6c8a9" /><text x={x(data.promiseAt!)} y="28" textAnchor="middle" fill="#d6c8a9" fontSize="11">PROMISE {time(data.promiseAt)}</text>
  </svg></div>;
}

export function Intelligence() {
  const demo = useDemo();
  const data = selectIntelligence(demo);
  const [detail, setDetail] = useState<"order" | "mint" | "supply">("order");
  const dialog = useRef<HTMLDialogElement>(null);
  const trigger = useRef<HTMLElement | null>(null);
  const open = (selection: typeof detail) => { trigger.current = document.activeElement as HTMLElement; setDetail(selection); dialog.current?.showModal(); };
  const facts = [
    ["Customer promise", `${demo.currentOrder.promisedSeconds / 60} min`],
    ["Kitchen prep estimate", clockDuration(data.prepSeconds + data.kitchenDelay)],
    [data.hq.sync.actualArrival ? "Rider at kitchen" : "Rider ETA from now", data.arrivalAt === null ? "—" : data.hq.sync.actualArrival ? "Recorded" : clockDuration(Math.max(0, data.arrivalAt - data.now))],
    [data.pickedUp ? "Recorded pickup" : "Target handoff", time(data.handoffAt)],
    [data.hq.sync.actualFood ? "Recorded food ready" : "Predicted food ready", time(data.foodAt)],
    [data.hq.sync.actualArrival ? "Recorded rider arrival" : "Predicted rider arrival", time(data.arrivalAt)],
    [data.pickedUp ? "Rider wait at pickup" : "Expected rider wait", data.riderWait === null ? "—" : `${data.riderWait} sec`],
    [data.pickedUp ? "Food hold at pickup" : "Expected food hold", data.foodWait === null ? "—" : `${data.foodWait} sec`],
  ];
  const promiseLabel = data.margin === null ? "Plan pending" : data.margin < 0 ? `${-data.margin}s beyond promise` : data.completed ? "Promise protected" : `${data.margin}s promise buffer`;
  return <div className={styles.surface}>
    <header className={styles.header}><Link href="/" className={styles.brand} aria-label="GO SERVE home">GO SERVE<span>SYSTEM INTELLIGENCE</span></Link><div className={styles.context}>Vijay Nagar <span>/</span> Dinner Rush<small>Protecting promise, preparation and pickup.</small></div><div className={styles.operating}><b><i />COORDINATING</b><span>SIMULATED</span></div><time>{time(data.now)}</time></header>
    <main id="main" className={styles.main}>
      <section className={styles.decision} aria-labelledby="live-decision"><div className={styles.decisionLead}><div className={styles.kicker}>01 / LIVE DECISION <span>{data.hq.hero.stage}</span></div><button className={styles.orderLink} onClick={() => open("order")} aria-label="Open GS-2847 intelligence detail">{data.hq.hero.id} <span>↗</span></button><h1 id="live-decision">{data.recommendation}</h1><p><span>WHY</span>{data.why}</p></div><dl className={styles.facts}>{facts.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
      <div className={styles.provenance} role="status"><span className={data.scenario !== "BASELINE" ? styles.amber : ""}>{data.scenarioNote}</span><span>{promiseLabel}</span></div>
      <section className={styles.sync} aria-labelledby="sync-heading"><div className={styles.sectionTop}><h2 id="sync-heading">02 / SYNCHRONIZATION</h2><span>One order. One timing axis.</span><b>{data.gap === null ? "Pending" : Math.abs(data.gap) <= 10 ? `Aligned · ${Math.abs(data.gap)}s window` : `${Math.abs(data.gap)}s ${data.gap > 0 ? "rider wait" : "food hold"}`}</b></div><Synchronization data={data} /><div className={styles.timelineFoot}><span>Kitchen start {data.planned ? time(data.start) : "pending"} · ○ projected / ● recorded milestones</span><span>Customer leg 05:30 + handoff 00:10</span></div></section>
      <section className={styles.signals} aria-labelledby="signals-heading"><h2 id="signals-heading">03 / SIGNALS IN</h2><div className={styles.signalGrid}>
        <div><span>KITCHEN</span><strong>{data.hq.loads[0].value}% <small>hot station</small></strong><p>{data.hq.kitchen.queued} queued · {clockDuration(data.prepSeconds + data.kitchenDelay)} prep</p></div>
        <div><span>RIDER</span><strong>Ravi Sharma</strong><button onClick={() => open("supply")}>Rider supply · WATCH ↗</button></div>
        <div><span>CUSTOMER</span><strong>{data.hq.hero.customer} <small>· {demo.currentOrder.promisedSeconds / 60}m promise</small></strong><p>{data.hq.hero.dish}</p></div>
        <div><span>INVENTORY</span><button className={styles.signalTitle} onClick={() => open("mint")}>Mint chutney ↗</button><p className={styles.amber}>{data.stockCover?.toFixed(1)}h cover · {data.stockCover !== null && data.stockCover < 0.5 ? "CRITICAL" : "LOW"}</p></div>
        <div><span>NETWORK</span><strong>Vijay Nagar</strong><p>{(demo.networkMetrics.sla * 100).toFixed(1)}% network SLA</p></div>
      </div></section>
      <section className={styles.serveSignal} aria-label="GO SERVE Signal"><span>↳</span><div><h2>GO SERVE SIGNAL</h2><p>{data.signal}</p></div></section>
      <div className={styles.lower}><section aria-labelledby="constraints-heading"><div className={styles.sectionTop}><h2 id="constraints-heading">04 / CONSTRAINTS & TRADE-OFFS</h2></div><ul className={styles.constraints}><li><span>01</span><div><strong>Protect food freshness</strong><p>{data.foodWait === null ? "Match completion to rider arrival." : `${data.foodWait}s food hold between readiness and rider arrival.`} Avoid completing food before pickup coverage is ready.</p></div></li><li><span>02</span><div><strong>Protect the customer promise</strong><p>{promiseLabel}. Prep and pickup must leave 05:40 for the customer leg and final handoff.</p></div></li><li><span>03</span><div><strong>Protect rider availability</strong><p>{data.riderWait ?? "Pending"}{data.riderWait === null ? " timing" : "s wait"} at the kitchen. {data.supplyText}</p></div></li><li><span>04</span><div><strong>Keep the order complete</strong><p>{data.inventoryText}</p></div></li></ul></section>
      <section aria-labelledby="forecast-heading"><div className={styles.sectionTop}><h2 id="forecast-heading">05 / NEXT 30 MINUTES</h2><span>Planning slots / 5 min</span></div><svg viewBox="0 0 520 130" className={styles.forecast} role="img" aria-label={`Demand 18 to 28 slots. Kitchen 29 to 31. Rider supply ${data.forecast[0].riders} to ${data.forecast[6].riders}. Demand crosses rider capacity at plus ${data.crossover} minutes.`}>{[20,25,30].map(n => <g key={n}><text x="0" y={109 - (n-16)*5} fill="#9aa798" fontSize="10">{n}</text><line x1="25" x2="510" y1={105-(n-16)*5} y2={105-(n-16)*5} stroke="#2a372e" /></g>)}{(["demand", "kitchen", "riders"] as const).map(key => <polyline key={key} points={data.forecast.map(point => `${25 + point.minute / 30 * 480},${105-(point[key]-16)*5}`).join(" ")} stroke={key === "demand" ? "#c0d6b2" : key === "kitchen" ? "#95a698" : "#cbb78f"} strokeWidth={key === "demand" ? 3 : 2} strokeDasharray={key === "riders" ? "5 4" : undefined} fill="none" />)}<text x="25" y="125" fill="#9aa798" fontSize="11">Now</text><text x="265" y="125" fill="#9aa798" fontSize="11">+15m</text><text x="478" y="125" fill="#9aa798" fontSize="11">+30m</text></svg><div className={styles.legend}><span>━ Demand</span><span>━ Kitchen capacity</span><span>┄ Rider supply</span></div><div className={styles.interpretation}>{[0,15,20,30].map(minute => { const point = data.forecast.find(item => item.minute === minute)!; return <div key={minute}><span>{minute ? `+${minute} MIN` : "NOW"}</span><p>{point.demand > point.riders ? minute === 30 ? "Promise at risk unless rider supply increases" : "Rider supply constrained" : minute === 0 ? "Capacity balanced" : "Kitchen and rider capacity cover demand"}</p></div>; })}</div><p className={styles.note}>Same deterministic outlook as HQ{data.scenario === "RIDER_SUPPLY" ? ", with the shared rider supply constraint" : ""}. Planning capacity, not a live dispatch prediction.</p></section></div>
      <section className={styles.trace} aria-labelledby="trace-heading"><div className={styles.sectionTop}><h2 id="trace-heading">06 / DECISION TRACE</h2><span>Inputs used for the current recommendation.</span></div><ol>{data.trace.map((item, index) => <li key={item.label}><span>{String(index + 1).padStart(2,"0")}</span><time>{item.at}</time><strong>{item.label}</strong><p>{item.detail}</p></li>)}</ol><p className={styles.note}>Current evaluation snapshot · deterministic rules and inputs. Applied actions are recorded below.</p>{demo.decisionHistory && demo.decisionHistory.length > 0 && <details className={styles.history}><summary>Applied decisions &amp; operational history · {demo.decisionHistory.length}</summary>{[...demo.decisionHistory].reverse().map(event => <article key={event.id}><time>{new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(event.at))}</time><div><h3>{event.what} · {event.decision}</h3><p>{event.signal}</p><p>{event.why}</p><p><strong>Protected:</strong> {event.constraint}</p><p><strong>Outcome:</strong> {event.consequence}</p></div></article>)}</details>}</section>
      <footer className={styles.architecture}><div>{["CUSTOMER", "PROMISE ENGINE", "KITCHEN", "HANDOFF", "RIDER", "CUSTOMER"].map((label,index) => <span key={index}>{label}{index < 5 && <i>→</i>}</span>)}</div><p>OBSERVE → PREDICT → SYNCHRONIZE → PROTECT</p></footer>
    </main>
    <dialog ref={dialog} className={styles.drawer} aria-labelledby="intelligence-detail-title" onKeyDown={event => { if (event.key !== "Tab") return; const items = Array.from(event.currentTarget.querySelectorAll<HTMLElement>("button, a[href], select, [tabindex=\"0\"]")); const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }} onClose={() => trigger.current?.isConnected && trigger.current.focus({ preventScroll: true })} onClick={event => { if (event.target === event.currentTarget) dialog.current?.close(); }}><div className={styles.drawerInner}><div className={styles.drawerTop}><span>SYSTEM INTELLIGENCE / DETAIL</span><button aria-label="Close intelligence detail" onClick={() => dialog.current?.close()}>×</button></div><h2 id="intelligence-detail-title">{detail === "order" ? data.hq.hero.id : detail === "mint" ? "Mint chutney" : "Rider supply"}</h2><p className={styles.note}>{data.scenarioNote}</p>
      {detail === "order" ? <><p>{data.hq.hero.customer} · {data.hq.hero.dish}</p><p>{data.hq.hero.stage} · {demo.deliveryAssignment ? "Assigned" : "Scheduled"} rider: Ravi Sharma</p><h3>{data.recommendation}</h3><p>{data.why}</p><dl className={styles.drawerFacts}>{facts.map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h3>HANDOFF CALCULATION</h3><p>{data.pickedUp ? "Pickup is recorded; the completed kitchen handoff is preserved." : "Handoff is the later of food readiness, rider arrival and the current clock."} Delivery estimate adds the shared 05:30 customer leg and 00:10 final handoff. {promiseLabel}.</p><h3>CURRENT EVALUATION</h3>{data.trace.map(item => <p className={styles.drawerTrace} key={item.label}><time>{item.at}</time><span>{item.label}<small>{item.detail}</small></span></p>)}<nav aria-label="Related product surfaces"><Link href="/customer">Customer ↗</Link><Link href="/kitchen">Kitchen ↗</Link><Link href="/rider">Rider ↗</Link><Link href="/hq">HQ ↗</Link></nav></> : detail === "mint" ? <><h3>{data.stockCover?.toFixed(1)}h STOCK COVER · {data.stockCover !== null && data.stockCover < 0.5 ? "CRITICAL" : "LOW"}</h3><p>{data.inventoryText}</p><p>Shared stock: {data.mint?.onHand} litres at {data.mint?.burnRate} litres per hour. Kitchen cover: {data.mint?.hoursRemaining.toFixed(1)} hours.</p>{data.scenario === "INVENTORY" && <p>The shared inventory scenario reduces cover to 24 minutes. Apply replenishment in Prototype to recover the 1.5-hour planning baseline.</p>}<p>{data.pickedUp ? "GS-2847 has already left the kitchen. Prepare the next batch for upcoming orders." : "Confirm the extra portion for GS-2847, then prepare the next batch. No automatic substitution is made."}</p></> : <><h3>DEMAND CROSSES SUPPLY AT +{data.crossover}M</h3><p>{data.supplyText}</p><table><caption>Illustrative slots per five-minute window</caption><thead><tr><th>Window</th><th>Demand</th><th>Kitchen</th><th>Riders</th></tr></thead><tbody>{data.forecast.map(point => <tr key={point.minute}><th>{point.minute ? `+${point.minute}m` : "Now"}</th><td>{point.demand}</td><td>{point.kitchen}</td><td>{point.riders}</td></tr>)}</tbody></table><p>Review available riders before the crossover. Planning slots are not rider counts. No assignment is changed by this view.</p></>}
    </div></dialog>
  </div>;
}




